### ISSUE TITLE
Ducks

### ISSUE THREAD

**Issue by RayzorDragon** [isuPatches/RockThePatch#311]
I feel the site would be improved with electrical ducks as an asset for users to interact with.

**Comment by isuPatches** [comment]
You say this in jest but I will implement it

**Comment by isuPatches** [comment]
You say this in jest but I will implement it

**Comment by RayzorDragon** [comment]
We shall see...

**Comment by isuPatches** [comment]
@RayzorDragon  you'll be happy to know I have taken your request into consideration and I have added ducks!  You can find this functionality here: https://www.rockthepatch.com/ducks.php
